default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000
  username: <%= ENV['POSTGRES_USER'] %>  # 環境変数からユーザー名を取得
  password: <%= ENV['POSTGRES_PASSWORD'] %>  # 環境変数からパスワードを取得
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>  # 環境変数からホストを取得、デフォルトは localhost
  port: <%= ENV['POSTGRES_PORT'] || 5432 %>  # 環境変数からポートを取得、デフォルトは 5432

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB_DEVELOPMENT'] %>  # 開発用データベース名

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB_TEST'] %>  # テスト用データベース名

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB_PRODUCTION'] %>  # 本番用データベース名